#!/usr/bin/python

import sys
import os
import subprocess


def main(fifo_path):
    """ Create a named pipe (aka fifo)

    Open the fifo for reading, execute whatever
    command was sent, and loop

    Exit if command is 'exit' and remove the fifo
    """
    if os.path.exists(fifo_path):
        sys.exit("Error: cmd.fifo already exists.\n"
                 "If no recieve-cmd process is running, "
                 "remove the file and try again")
    os.mkfifo(fifo_path)
    while True:
        with open(fifo_path, "r") as fd:
            data = fd.read()
            if not data:
                continue
            if data == "exit\n":
                break
            try:
                subprocess.call(data, shell=True)
            except Exception as e:
                sys.stderr.write(str(e))
                sys.stdout.flush()
    os.remove(fifo_path)


if __name__ == "__main__":
    fifo_path = "cmd.fifo"
    try:
        main(fifo_path)
    except KeyboardInterrupt:
        print("Interrupted by user, cleaning up")
        try:
            os.remove(fifo_path)
        except:
              pass
