#!/usr/bin/python

import os
import sys

def main():
    cmd = " ".join(sys.argv[1:])
    fifo_path = "cmd.fifo"
    if not os.path.exists(fifo_path):
        sys.exit("Error: could not find cmd.fifo.\n"
                 "Make sure recieve-cmd is running")
    try:
        with open(fifo_path, "w") as fd:
            fd.write(cmd + "\n")
    except Exception as e:
        sys.exit("Error: could not write to fifo.\n" + str(e))

if __name__ == "__main__":
    main()

